name: goodie
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.7.2
  provider: ^6.0.5
  firebase_core: ^2.15.0
  supabase: ^1.9.9
  cloud_firestore: ^4.8.4
  cached_network_image: ^3.1.0
  google_maps_flutter: ^2.4.0
  latlong2: ^0.8.0
  location: ^5.0.2+1
  url_launcher: ^6.1.12
  image_picker: ^1.0.2
  path_provider: ^2.1.0
  photo_manager: ^2.7.1
  photo_view: ^0.14.0
  crypto: ^3.0.1
  exif: ^3.1.4
  flutter_google_maps_webservices: ^1.1.1
  firebase_storage: ^11.2.6
  video_player: ^2.7.1
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2
  preload_page_view: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
